apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - nodePort: 32010       # ✅ Changed to a free NodePort
      port: 9000
      targetPort: 8080
  selector:
    app: hiring-app         # ✅ Match with Deployment label
